### ISSUE TITLE
Area Carousel Improvement

### ISSUE THREAD

**Issue by benClmnt** [indocom/visintus-client#3]
Carousel could be improved by making automatic scrolling and manual controls. 
Here's a reference I've found: 

- https://medium.com/better-programming/make-a-slideshow-with-automatic-and-manual-controls-using-html-css-and-javascript-b7e9305168f9

- https://medium.com/javascript-in-plain-english/automatic-slideshow-carousel-in-react-89042c4dedb2

**Comment by AudreyFelicio** [comment]
carousel issue solved
